[workspace]
members = [
    "core",
    "memory",
    "vector",
    "fusion",
    "persona",
    "crown",
    "rag",
    "numeric",
    "narrative",
    "insight",
    "kimicho",
    "k2coder",
    "chakrapulse",
    "razor",
    "inanna",
]
resolver = "2"
