version: '3.8'
services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:latest
    ports:
      - "3000:8080"
    environment:
      FASTAPI_BASE_URL: ${FASTAPI_BASE_URL:-http://localhost:8000}
    restart: unless-stopped
