site_name: ABZU Documentation
docs_dir: docs
nav:
  - Home: index.md
  - Code Index: code_index.md
plugins:
  - search
  - mkdocs-simple-hooks:
      hooks:
        on_pre_build: "scripts.build_index:run"
