priorities:
  memory_store: 1
  chat_gateway: 2
  crown_llm: 2
  audio_device: 3
  avatar: 4
  video: 5

remote_agents:
  - name: inanna_core
    source: git+https://example.com/inanna-core.git
  - name: crown_llm
    source: git+https://example.com/crown-llm.git

messaging:
  lifecycle_bus: tcp://localhost:5555
  recovery_channel: tcp://localhost:5556
