[package]
name = "neoabzu-inanna"
version = "0.1.0"
edition = "2021"

[lib]
name = "neoabzu_inanna"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.21.2", features = ["extension-module"] }
neoabzu-chakrapulse = { path = "../chakrapulse" }
