global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['api:8000']
  - job_name: 'mediasoup'
    static_configs:
      - targets: ['mediasoup:3000']
  - job_name: 'gpu'
    static_configs:
      - targets: ['gpu-exporter:9400']
