- name: bug
  color: d73a4a
  description: Something isn't working
- name: enhancement
  color: a2eeef
  description: New feature or request
- name: plugin
  color: 0e8a16
  description: Proposed plugin contributions
- name: ritual
  color: 5319e7
  description: Proposed ritual practices
- name: question
  color: d876e3
  description: Further information is requested
