# Crown agent configuration
# Environment variables can override these values:
#   GLM_API_URL   -> glm_api_url
#   GLM_API_KEY   -> glm_api_key
#   MODEL_PATH    -> model_path
#   MEMORY_DIR    -> memory_dir
#   SERVANT_MODELS -> servant_models

glm_api_url: https://glm.example.com/glm41v_9b
glm_api_key: your-api-key
model_path: models/GLM-4.1V-9B
memory_dir: data/vector_memory
servant_models:
  deepseek: http://localhost:8002
  mistral: http://localhost:8003
