dependencies: []
enable_ai_handover: false
ai_agent:
  name: ""
  endpoint: ""
  auth_token: ""
  models: []
components:
  - name: memory_store
    priority: 1
    command: "echo 'starting memory_store'"
  - name: chat_gateway
    priority: 2
    command: "echo 'starting chat_gateway'"
  - name: crown_llm
    priority: 2
    command: "echo 'starting crown_llm'"
  - name: vision_adapter
    priority: 2
    command: "echo 'starting vision_adapter'"
    stop: "echo 'stopping vision_adapter'"
    quarantine_on_fail: true
  - name: audio_device
    priority: 3
    command: "echo 'starting audio_device'"
  - name: avatar
    priority: 4
    command: "echo 'starting avatar'"
  - name: video
    priority: 5
    command: "echo 'starting video'"
