# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
# ruff: noqa
# flake8: noqa
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import vector_pb2 as vector__pb2


class VectorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Init = channel.unary_unary(
            "/neoabzu.vector.VectorService/Init",
            request_serializer=vector__pb2.InitRequest.SerializeToString,
            response_deserializer=vector__pb2.InitResponse.FromString,
        )
        self.Search = channel.unary_unary(
            "/neoabzu.vector.VectorService/Search",
            request_serializer=vector__pb2.SearchRequest.SerializeToString,
            response_deserializer=vector__pb2.SearchResponse.FromString,
        )


class VectorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Init(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_VectorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Init": grpc.unary_unary_rpc_method_handler(
            servicer.Init,
            request_deserializer=vector__pb2.InitRequest.FromString,
            response_serializer=vector__pb2.InitResponse.SerializeToString,
        ),
        "Search": grpc.unary_unary_rpc_method_handler(
            servicer.Search,
            request_deserializer=vector__pb2.SearchRequest.FromString,
            response_serializer=vector__pb2.SearchResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "neoabzu.vector.VectorService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class VectorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Init(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/neoabzu.vector.VectorService/Init",
            vector__pb2.InitRequest.SerializeToString,
            vector__pb2.InitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Search(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/neoabzu.vector.VectorService/Search",
            vector__pb2.SearchRequest.SerializeToString,
            vector__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
