# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# ruff: noqa
# flake8: noqa
# source: vector.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0cvector.proto\x12\x0eneoabzu.vector"\r\n\x0bInitRequest"\x1f\n\x0cInitResponse\x12\x0f\n\x07message\x18\x01 \x01(\t",\n\rSearchRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05top_n\x18\x02 \x01(\r">\n\x0cSearchResult\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x12\x11\n\tembedding\x18\x03 \x03(\x02"?\n\x0eSearchResponse\x12-\n\x07results\x18\x01 \x03(\x0b\x32\x1c.neoabzu.vector.SearchResult2\x9b\x01\n\rVectorService\x12\x41\n\x04Init\x12\x1b.neoabzu.vector.InitRequest\x1a\x1c.neoabzu.vector.InitResponse\x12G\n\x06Search\x12\x1d.neoabzu.vector.SearchRequest\x1a\x1e.neoabzu.vector.SearchResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "vector_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_INITREQUEST"]._serialized_start = 32
    _globals["_INITREQUEST"]._serialized_end = 45
    _globals["_INITRESPONSE"]._serialized_start = 47
    _globals["_INITRESPONSE"]._serialized_end = 78
    _globals["_SEARCHREQUEST"]._serialized_start = 80
    _globals["_SEARCHREQUEST"]._serialized_end = 124
    _globals["_SEARCHRESULT"]._serialized_start = 126
    _globals["_SEARCHRESULT"]._serialized_end = 188
    _globals["_SEARCHRESPONSE"]._serialized_start = 190
    _globals["_SEARCHRESPONSE"]._serialized_end = 253
    _globals["_VECTORSERVICE"]._serialized_start = 256
    _globals["_VECTORSERVICE"]._serialized_end = 411
# @@protoc_insertion_point(module_scope)
