[package]
name = "neoabzu-razor"
version = "0.1.0"
edition = "2021"

[lib]
name = "neoabzu_razor"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"] }
neoabzu-chakrapulse = { path = "../chakrapulse" }
