[package]
name = "neoabzu-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "neoabzu_core"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module", "auto-initialize"] }
