[package]
name = "neoabzu-numeric"
version = "0.1.0"
edition = "2021"

[lib]
name = "neoabzu_numeric"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"] }
numpy = "0.21"
ndarray = "0.15"
