[package]
name = "neoabzu-chakrapulse"
version = "0.1.0"
edition = "2021"

[lib]
name = "neoabzu_chakrapulse"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
once_cell = "1.18"
crossbeam-channel = "0.5"
pyo3 = { version = "0.21.2", features = ["extension-module"] }
