[package]
name = "neoabzu-insight"
version = "0.1.0"
edition = "2021"

[lib]
name = "neoabzu_insight"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"] }

[features]
default = []
