name: Alpha Gate

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 6 * * 1'

jobs:
  alpha-gate:
    name: Run Alpha v0.1 gate
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      PYTHONUNBUFFERED: '1'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Restore pip cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt', 'dev-requirements.txt', 'pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Restore build cache
        uses: actions/cache@v4
        with:
          path: dist
          key: ${{ runner.os }}-alpha-gate-dist-${{ hashFiles('pyproject.toml', 'setup.cfg') }}
          restore-keys: |
            ${{ runner.os }}-alpha-gate-dist-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
          pip install build pytest

      - name: Refresh Crown identity when doctrine changes
        run: |
          set -euo pipefail
          mkdir -p logs/identity_refresh
          BASE_REF="${{ github.event.before }}"
          if [ -z "$BASE_REF" ] || [ "$BASE_REF" = "0000000000000000000000000000000000000000" ]; then
            BASE_REF="$(git rev-list --max-parents=0 HEAD)"
          fi
          CHANGED_FILES="$(git diff --name-only "$BASE_REF" HEAD || true)"
          if echo "$CHANGED_FILES" | grep -E '^(docs/project_mission_vision\.md|docs/persona_api_guide\.md|GENESIS/|CODEX/ACTIVATIONS/|INANNA_AI/)' >/dev/null; then
            echo "Doctrine updates detected; refreshing Crown identity"
            python scripts/refresh_crown_identity.py --use-stub --log-dir logs/identity_refresh | tee logs/identity_refresh/latest_refresh.json
          else
            echo "No doctrine updates detected; skipping identity refresh"
          fi

      - name: Prepare mock connector endpoints
        run: |
          mkdir -p mock_connectors
          echo 'ok' > mock_connectors/health
          nohup python -m http.server 8000 --directory mock_connectors >mock_connectors/server.log 2>&1 &
          echo $! > mock_connectors/server.pid

      - name: Run Alpha gate
        run: |
          bash scripts/run_alpha_gate.sh --check-connectors

      - name: Record gate success in changelog
        if: success()
        run: |
          mkdir -p logs/alpha_gate
          printf '\n### Alpha gate validation %s\n- workflow run: %s\n' "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" "$GITHUB_RUN_ID" >> CHANGELOG.md
          cp CHANGELOG.md logs/alpha_gate/CHANGELOG.md

      - name: Upload Alpha gate logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: alpha-gate-logs
          path: |
            logs/alpha_gate/
            logs/identity_refresh/
            mock_connectors/server.log
          if-no-files-found: warn

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: alpha-gate-dist
          path: dist/
          if-no-files-found: warn

      - name: Stop mock connector server
        if: always()
        run: |
          if [ -f mock_connectors/server.pid ]; then
            kill "$(cat mock_connectors/server.pid)" || true
          fi
