---
name: CI

'on':
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            pyproject.toml
            requirements.txt
            dev-requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev] --no-deps
          pip install flake8 pytest
      - name: Lint
        run: flake8 --select=E9,F63,F7,F82 tests/test_github_scraper.py
      - name: Test
        run: pytest tests/test_github_scraper.py
