name: CI

on:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure docs updated
        run: |
          git fetch origin $GITHUB_BASE_REF --depth=1
          CODE_CHANGED=$(git diff --name-only origin/$GITHUB_BASE_REF...HEAD | grep -E '\.py$' | grep -v '^tests/' || true)
          DOCS_CHANGED=$(git diff --name-only origin/$GITHUB_BASE_REF...HEAD | grep -E '^docs/.*\.md$' || true)
          if [ -n "$CODE_CHANGED" ] && [ -z "$DOCS_CHANGED" ]; then
            echo "Modules were modified without corresponding documentation updates:"
            echo "$CODE_CHANGED"
            exit 1
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: |
            pyproject.toml
            requirements.txt
            dev-requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r dev-requirements.txt
          pip install -e .
          pip install ruff black mypy pytest pytest-cov

      - name: Verify required pytest plugins
        run: python - <<'PY'
import importlib, sys
sys.exit(0 if importlib.util.find_spec('pytest_cov') else 1)
PY

      - name: Ruff
        run: ruff check .

      - name: Black
        run: black --check --exclude tests .

      - name: Mypy
        run: mypy

      - name: Run tests
        env:
          PYTHONPATH: src
        run: pytest --cov

      - name: Profiling
        run: python -m cProfile -m task_profiling

      - name: Health scan
        run: |
          set -o pipefail
          python start_spiral_os.py --dry-run 2>&1 | tee health.log
          if grep -E "ERROR|MISSING" health.log; then
            exit 1
          fi

      - name: Failure guidance
        if: failure()
        run: |
          echo "CI checks failed. See the onboarding and architecture guides for help:" \
          && echo "https://github.com/$GITHUB_REPOSITORY/blob/$GITHUB_BASE_REF/docs/developer_onboarding.md" \
          && echo "https://github.com/$GITHUB_REPOSITORY/blob/$GITHUB_BASE_REF/docs/architecture.md"
