name: CI

on:
  push:
  pull_request:

# Reusable anchors keep the workflow maintainable
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - &checkout
        name: Checkout repository
        uses: actions/checkout@v4

      - &setup-python
        name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip  # Cache dependencies for speed
          cache-dependency-path: |
            pyproject.toml
            requirements.txt
            dev-requirements.txt

      - &install-deps
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev] --no-deps
          pip install ruff black mypy bandit pytest

      - name: Ruff
        run: ruff .  # Fail on any lint warning

      - name: Black
        run: black --check .  # Enforce formatting

      - name: Mypy
        run: mypy .  # Static type checking

      - name: Bandit
        run: bandit -r . -x tests  # Security analysis

  tests:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - *checkout
      - *setup-python
      - *install-deps
      - name: Coverage
        run: |
          coverage run -m pytest
          coverage html
          coverage report
      - name: Upload coverage HTML
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov
