---
name: CI

'on':
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            pyproject.toml
            requirements.txt
            dev-requirements.txt
      - name: Bootstrap
        run: bash scripts/bootstrap.sh
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev] --no-deps
          pip install pre-commit pytest pytest-cov coverage-badge mypy
      - name: Lint
        run: pre-commit run --all-files --show-diff-on-failure
      - name: Type check
        run: mypy .
      - name: Test
        run: pytest --maxfail=1 --strict-markers -m "not hardware" --cov=./ --cov-report=xml
      - name: Coverage report
        run: coverage report --fail-under=80
      - name: Generate coverage badge
        run: coverage-badge -o coverage.svg -f
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: |
            coverage.xml
            coverage.svg
      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
