name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            pyproject.toml
            requirements.txt
            dev-requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev] --no-deps
          pip install pre-commit mypy pytest pytest-cov
      - name: Run pre-commit
        run: pre-commit run --all-files
      - name: Run mypy
        run: mypy --strict .
      - name: Run tests
        run: pytest --cov=src --cov-report=xml
