name: CI

on:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: |
            pyproject.toml
            requirements.txt
            dev-requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r requirements.txt -r dev-requirements.txt ruff black mypy pytest pytest-cov

      - name: Verify required pytest plugins
        run: python - <<'PY'
import importlib, sys
sys.exit(0 if importlib.util.find_spec('pytest_cov') else 1)
PY

      - name: Ruff
        run: ruff check .

      - name: Black
        run: black --check --exclude tests .

      - name: Mypy
        run: mypy

      - name: Run tests
        run: pytest --cov

      - name: Profiling
        run: python -m cProfile -m task_profiling

      - name: Health scan
        run: |
          set -o pipefail
          python start_spiral_os.py --dry-run 2>&1 | tee health.log
          if grep -E "ERROR|MISSING" health.log; then
            exit 1
          fi
