name: Insight matrix update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Run insight compiler
        run: |
          python - <<'PY'
          from corpus_memory_logging import load_interactions
          from insight_compiler import update_insights
          update_insights(load_interactions())
          PY
      - name: Commit insight matrix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add insight_matrix.json insight_manifest.json CHANGELOG_insight_matrix.md || true
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update insight matrix"
            git push
          fi
