name: Nightly CI

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  qa:
    name: Lint and Test
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: src
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r dev-requirements.txt
          pip install -e .
      - name: Run pre-commit
        run: pre-commit run --all-files
      - name: Run pytest
        run: pytest --cov --cov-fail-under=90 --junitxml=pytest.xml
      - name: Generate protocol refinement task
        run: python scripts/generate_protocol_task.py
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: pytest.xml
          if-no-files-found: ignore
