name: Retraining pipeline

on:
  push:
    tags:
      - '*'

jobs:
  retrain:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    concurrency:
      group: retraining
      cancel-in-progress: false
    environment:
      name: model-deployment
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
      - name: Run auto retrain
        run: python auto_retrain.py --run
      - name: Upload retraining log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: retraining-log
          path: docs/retraining_log.md
